=== hugovidal04/Practica-Lima/Segundo Trimestre/Prueba/EJERCICIO02_XSD/empresa.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="empresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="clientes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="cliente" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"></xs:element>
                                        <xs:element name="apellidos" type="xs:string"></xs:element>
                                        <xs:element name="email">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="tipo" type="xs:string"></xs:attribute>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="telefono"  type="xs:integer"></xs:element>
                                        <xs:element name="direccion">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="calle" type="xs:string"></xs:element>
                                                    <xs:element name="ciudad" type="xs:string"></xs:element>
                                                    <xs:element name="pais" type="xs:string"></xs:element>
                                                    <xs:element name="codigoPostal" type="xs:integer"></xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="tipo"  type="xs:string"></xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="piezas">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="pieza" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"></xs:element>
                                        <xs:element name="descripcion" type="xs:string"></xs:element>
                                        <xs:element name="precio">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:decimal">
                                                        <xs:attribute name="moneda" type="xs:string"></xs:attribute>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="stock" type="xs:integer"></xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id"  type="xs:string"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="ventas">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="venta" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="clienteId"  type="xs:string"></xs:element>
                                        <xs:element name="fecha" type="xs:date"></xs:element>
                                        <xs:element name="detalles">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="detalle" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="piezaId" type="xs:string"></xs:element>
                                                                <xs:element name="cantidad" type="xs:integer"></xs:element>
                                                            </xs:sequence>  
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id"  type="xs:string"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== hugovidal04/Practica-Lima/Segundo Trimestre/Prueba/EJERCICIO02_XSD/empresa.xml
<?xml version="1.0" encoding="UTF-8"?>

<empresa
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="empresa.xsd">
    <clientes>
        <cliente id="C001">
            <nombre>Juan</nombre>
            <apellidos>Pérez</apellidos>
            <email tipo="personal">juanperez@email.com</email>
            <telefono>987987987</telefono>
            <direccion tipo="domicilio">
                <calle>Calle Falsa 123</calle>
                <ciudad>Pontevedra</ciudad>
                <pais>España</pais>
                <codigoPostal>36001</codigoPostal>
            </direccion>
        </cliente>
        <cliente id="C002">
            <nombre>Maria</nombre>
            <apellidos>López</apellidos>
            <email tipo="empresa">marialopez@email.com</email>
            <telefono>987654321</telefono>
            <direccion tipo="domicilio">
                <calle>Avenida del Progreso 321</calle>
                <ciudad>Santiago</ciudad>
                <pais>España</pais>
                <codigoPostal>15995</codigoPostal>
            </direccion>
        </cliente>
    </clientes>

    <piezas>
        <pieza id="P001">
            <nombre>Tarjeta Gráfica XYZ 123</nombre>
            <descripcion>Tarjeta gráfica de alto rendimiento para gaming y diseño gráfico</descripcion>
            <precio moneda="€">299.99</precio>
            <stock>10</stock>
        </pieza>
        <pieza id="P002">
            <nombre>Disco Duro SSD 1TB Marca ABC</nombre>
            <descripcion>Disco duro SSD de 1TB, velocidad de lectura/escritura superior</descripcion>
            <precio moneda="$">109.99</precio>
            <stock>15</stock>
        </pieza>
    </piezas>

    <ventas>
        <venta id="V001">
            <clienteId>C001</clienteId>
            <fecha>2024-01-15</fecha>
            <detalles>
                <detalle>
                    <piezaId>P001</piezaId>
                    <cantidad>1</cantidad>
                </detalle>
                <detalle>
                    <piezaId>P002</piezaId>
                    <cantidad>2</cantidad>
                </detalle>
            </detalles>
        </venta>
        <venta id="V002">
            <clienteId>C002</clienteId>
            <fecha>2024-02-20</fecha>
            <detalles>
                <detalle>
                    <piezaId>P002</piezaId>
                    <cantidad>1</cantidad>
                </detalle>
            </detalles>
        </venta>
    </ventas>
</empresa>
