=== hugovidal04/Practica-Lima/Segundo Trimestre/Repaso_1/Repaso_11.dtd
<!ELEMENT informacion_juegos (sistemas, videojuegos)>
<!ELEMENT sistemas (sistema+)>
<!ELEMENT sistema (nombre, lanzamiento, ventas, companhia)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT lanzamiento (#PCDATA)>
<!ELEMENT ventas (#PCDATA)>
<!ATTLIST ventas unidad CDATA #REQUIRED>
<!ELEMENT companhia (#PCDATA)>
<!ELEMENT videojuegos (videojuego+)>
<!ATTLIST videojuego id ID #REQUIRED>
<!ELEMENT videojuego (titulo, desarrollador, lanzamiento, ventas, plataformas)>
<!ELEMENT titulo (#PCDATA)>
<!ATTLIST titulo genero CDATA #REQUIRED>
<!ELEMENT desarrollador (#PCDATA)>
<!ELEMENT lanzamiento (#PCDATA)>
<!ELEMENT ventas (#PCDATA)>
<!ELEMENT plataformas (plataforma+)>
<!ELEMENT plataforma (#PCDATA)>

=== hugovidal04/Practica-Lima/Segundo Trimestre/Repaso_1/Repaso_11.xml
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE informacion_juegos SYSTEM "Repaso_11.dtd">
<informacion_juegos> 
    <sistemas> 
        <sistema> 
            <nombre>Wii U</nombre> 
            <lanzamiento>2012</lanzamiento> 
            <ventas unidad="M">13.56</ventas> 
            <companhia>Nintendo</companhia> 
        </sistema> 
        <sistema> 
            <nombre>Nintendo Switch</nombre> 
            <lanzamiento>2017</lanzamiento> 
            <ventas unidad="M">138.04</ventas> 
            <companhia>Nintendo</companhia> 
        </sistema> 
        <sistema> 
            <nombre>PlayStation 3</nombre> 
            <lanzamiento>2006</lanzamiento> 
            <ventas unidad="M">87.4</ventas> 
            <companhia>Sony</companhia> 
        </sistema> 
        <sistema> 
            <nombre>PlayStation 4</nombre> 
            <lanzamiento>2013</lanzamiento> 
            <ventas unidad="M">115.9</ventas> 
            <companhia>Sony</companhia> 
        </sistema> 
        <sistema> 
            <nombre>PlayStation 5</nombre> 
            <lanzamiento>2020</lanzamiento> 
            <ventas unidad="M">54.47</ventas> 
            <companhia>Sony</companhia> 
        </sistema> 
        <sistema> 
            <nombre>PlayStation Vita</nombre> 
            <lanzamiento>2011</lanzamiento> 
            <ventas unidad="M">15</ventas> 
            <companhia>Sony</companhia> 
        </sistema> 
        <sistema> 
            <nombre>Xbox 360</nombre> 
            <lanzamiento>2005</lanzamiento> 
            <ventas unidad="M">84</ventas> 
            <companhia>Microsoft</companhia> 
        </sistema> 
        <sistema> 
            <nombre>Xbox One</nombre> 
            <lanzamiento>2013</lanzamiento> 
            <ventas unidad="M">51</ventas> 
            <companhia>Microsoft</companhia> 
        </sistema> 
        <sistema> 
            <nombre>Xbox Series</nombre> 
            <lanzamiento>2020</lanzamiento> 
            <ventas unidad="M">27.72</ventas> 
            <companhia>Microsoft</companhia> 
        </sistema> 
        <sistema> 
            <nombre>PC</nombre> 
            <lanzamiento>1981</lanzamiento> 
            <ventas unidad="M">Incalculables</ventas> 
            <companhia>Varios</companhia> 
        </sistema> 
    </sistemas> 
 
    <videojuegos> 
        <videojuego id="v001"> 
            <titulo genero="Aventura">The Legend of Zelda: Breath of the Wild</titulo> 
            <desarrollador>Nintendo</desarrollador> 
            <lanzamiento>2017</lanzamiento> 
            <ventas unidad="M">23.20</ventas> 
            <plataformas> 
                <plataforma>Nintendo Switch</plataforma> 
                <plataforma>Wii U</plataforma> 
            </plataformas> 
        </videojuego> 
        <videojuego id="v002"> 
            <titulo genero="AcciÃ³n, Aventura">Grand Theft Auto V</titulo> 
            <desarrollador>Rockstar Games</desarrollador> 
            <lanzamiento>2013</lanzamiento> 
            <ventas unidad="M">160</ventas> 
            <plataformas> 
                <plataforma>PlayStation 3</plataforma> 
                <plataforma>PlayStation 4</plataforma> 
                <plataforma>Xbox 360</plataforma> 
                <plataforma>Xbox One</plataforma> 
                <plataforma>PC</plataforma> 
            </plataformas> 
        </videojuego> 
        <videojuego id="v003"> 
            <titulo genero="Sandbox, RPG">Yakuza: Like a Dragon</titulo> 
            <desarrollador>Sega</desarrollador> 
            <lanzamiento>2020</lanzamiento> 
            <ventas unidad="M">1.8</ventas> 
            <plataformas> 
                <plataforma>PlayStation 4</plataforma> 
                <plataforma>PlayStation 5</plataforma> 
                <plataforma>Xbox One</plataforma> 
                <plataforma>Xbox Series</plataforma> 
                <plataforma>PC</plataforma> 
            </plataformas> 
        </videojuego> 
        <videojuego id="v004"> 
            <titulo genero="Action RPG">Bloodborne</titulo> 
            <desarrollador>FromSoftware</desarrollador> 
            <lanzamiento>2015</lanzamiento> 
            <ventas unidad="M">3</ventas> 
            <plataformas> 
                <plataforma>PlayStation 4</plataforma> 
            </plataformas> 
        </videojuego> 
        <videojuego id="v005"> 
            <titulo genero="RPG">Persona 4 Golden</titulo> 
            <desarrollador>Atlus</desarrollador> 
            <lanzamiento>2012</lanzamiento> 
            <ventas unidad="M">1.5</ventas> 
            <plataformas> 
                <plataforma>PlayStation Vita</plataforma> 
                <plataforma>PC</plataforma> 
            </plataformas> 
        </videojuego> 
    </videojuegos> 
</informacion_juegos>
